# Generated by Django 2.1.3 on 2019-01-07 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irfanApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='files_tab',
        ),
    ]
